esphome:
  name: orbit_water_valve
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "oceania2.lan"
  password: "qq1ww2ee3rr4tt5yy6uu7ii8oo"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sw Dual Test Fallback Hotspot"
    password: "tz0osTYFAx88"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'espha39it9'

ota:
  password: 'espha39it9'

web_server:
  port: 80

binary_sensor:
  - platform: status
    name: "SW dual 01 Status"


switch:
  - platform: orbit_water_valve
    name: "Test dual"
    pin_a: GPIO0
    pin_b: GPIO2